#!/usr/bin/python
from mnemonic import Mnemonic
from binascii import hexlify, unhexlify
import sys

phrase = sys.stdin.readline().strip()
print hexlify(Mnemonic.to_seed(phrase, passphrase = 'TREZOR'))
